<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14.0</LangVersion>
    <RootNamespace>Boop.Win7ify.Core</RootNamespace>
    <AssemblyName>Boop.Win7ify.Core</AssemblyName>
  </PropertyGroup>
</Project>