plugins { id 'com.android.application' }
apply from: rootProject.file('split-app-shell.gradle')
android {
    namespace 'com.boop.shieldapp'
    defaultConfig {
        applicationId 'com.boop.shieldoverlay'
        versionCode 218
        versionName '1.2.218-shield'
    }
    buildTypes { debug { signingConfig signingConfigs.boopDev } }
}
dependencies { implementation project(':assistant-lib') }
