plugins {
    id 'com.android.library'
}

android {
    namespace 'com.boop.shieldoverlay'
    compileSdk 36
    defaultConfig {
        minSdk 26
        targetSdk 36
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.squareup.okhttp3:okhttp-tls:4.12.0'
    implementation 'com.google.zxing:core:3.5.3'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
    testImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
}
