package com.boop.launcher;

import android.appwidget.AppWidgetHostView;
import android.content.*;
import android.graphics.Color;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;

public final class WorkspaceView extends FrameLayout {
 public interface Listener{void launch(WorkspaceItem item);void changed();void emptyLongPress(float x,float y);void openDrawer();}
 private final ArrayList<WorkspaceItem> items;private final Listener listener;private final WidgetController widgets;private final Handler handler=new Handler(Looper.getMainLooper());
 private final int slop,removeBand,drawerThreshold,pageThreshold;private int currentPage=0;
 public WorkspaceView(Context c,ArrayList<WorkspaceItem> items,WidgetController widgets,Listener listener){super(c);this.items=items;this.widgets=widgets;this.listener=listener;setBackgroundColor(Color.BLACK);setContentDescription("Home canvas");setMotionEventSplittingEnabled(false);slop=ViewConfiguration.get(c).getScaledTouchSlop();removeBand=dp(112);drawerThreshold=dp(72);pageThreshold=dp(64);setOnTouchListener(new EmptyTouch());}
 private int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}
 public int currentPage(){return currentPage;}
 public void refresh(){removeAllViews();post(this::drawItems);}
 public void addApp(AppEntry app){WorkspaceItem i=new WorkspaceItem();i.component=app.component.flattenToString();i.label=app.label;i.page=currentPage;if(!findOpenSlot(i,currentPage)){i.page=maxPage()+1;currentPage=i.page;findOpenSlot(i,currentPage);}items.add(i);listener.changed();refresh();}
 public void addWidget(int id){WorkspaceItem i=new WorkspaceItem();i.widgetId=id;i.label="Widget";i.w=.84f;i.h=.24f;i.page=currentPage;if(!findOpenSlot(i,currentPage)){i.page=maxPage()+1;currentPage=i.page;findOpenSlot(i,currentPage);}items.add(i);listener.changed();refresh();}
 private boolean findOpenSlot(WorkspaceItem item,int page){item.page=page;for(float y=.05f;y+item.h<.96f;y+=.06f)for(float x=.04f;x+item.w<.97f;x+=.05f){item.x=x;item.y=y;if(!overlaps(item,null))return true;}item.x=.05f;item.y=.08f;return false;}
 private boolean overlaps(WorkspaceItem candidate,WorkspaceItem except){for(WorkspaceItem i:items){if(i==except||i.page!=candidate.page)continue;if(candidate.x<i.x+i.w&&candidate.x+candidate.w>i.x&&candidate.y<i.y+i.h&&candidate.y+candidate.h>i.y)return true;}return false;}
 private int maxPage(){int m=0;for(WorkspaceItem i:items)m=Math.max(m,i.page);return m;}
 private boolean pageExists(int page){if(page==0)return true;for(WorkspaceItem i:items)if(i.page==page)return true;return false;}
 private void goPage(int page){if(page<0||!pageExists(page))return;currentPage=page;refresh();}
 private void compactPages(){TreeSet<Integer> used=new TreeSet<>();for(WorkspaceItem i:items)used.add(i.page);if(used.isEmpty()){currentPage=0;return;}HashMap<Integer,Integer> map=new HashMap<>();int n=0;for(int old:used)map.put(old,n++);Integer mapped=map.get(currentPage);for(WorkspaceItem i:items)i.page=map.get(i.page);currentPage=mapped==null?Math.min(currentPage,n-1):mapped;}
 private void removeItem(WorkspaceItem item){items.remove(item);if(item.widgetId>=0)widgets.deleteId(item.widgetId);compactPages();listener.changed();refresh();}
 private void drawItems(){int W=getWidth(),H=getHeight();if(W<=0||H<=0)return;ArrayList<WorkspaceItem> stale=new ArrayList<>();for(WorkspaceItem item:new ArrayList<>(items)){if(item.page!=currentPage)continue;if(item.widgetId>=0){AppWidgetHostView host=widgets.createView(getContext(),item.widgetId);if(host==null){stale.add(item);continue;}WidgetFrame frame=new WidgetFrame(item,host);FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(Math.max(dp(120),(int)(item.w*W)),Math.max(dp(96),(int)(item.h*H)));p.leftMargin=(int)(item.x*W);p.topMargin=(int)(item.y*H);addView(frame,p);frame.post(frame::notifySize);continue;}LinearLayout tile=new LinearLayout(getContext());tile.setOrientation(LinearLayout.VERTICAL);tile.setGravity(Gravity.CENTER);tile.setBackgroundColor(Color.TRANSPARENT);ImageView icon=new ImageView(getContext());try{icon.setImageDrawable(getContext().getPackageManager().getActivityIcon(item.componentName()));}catch(Exception e){icon.setImageResource(android.R.drawable.sym_def_app_icon);}tile.addView(icon,new LinearLayout.LayoutParams(-1,0,1));TextView label=new TextView(getContext());label.setText(item.label);label.setTextColor(Color.WHITE);label.setTextSize(13);label.setGravity(Gravity.CENTER);label.setMaxLines(2);tile.addView(label,new LinearLayout.LayoutParams(-1,dp(38)));tile.setContentDescription(item.label);FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(Math.max(dp(64),(int)(item.w*W)),Math.max(dp(84),(int)(item.h*H)));p.leftMargin=(int)(item.x*W);p.topMargin=(int)(item.y*H);tile.setOnTouchListener(new ItemTouch(item,tile));addView(tile,p);}if(!stale.isEmpty()){for(WorkspaceItem i:stale){items.remove(i);widgets.deleteId(i.widgetId);}compactPages();listener.changed();post(this::refresh);}}
 private final class ItemTouch implements OnTouchListener{final WorkspaceItem item;final View view;float downX,downY,startX,startY;boolean dragging,moved;Runnable hold;ItemTouch(WorkspaceItem i,View v){item=i;view=v;}
  public boolean onTouch(View v,MotionEvent e){switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:downX=e.getRawX();downY=e.getRawY();startX=item.x;startY=item.y;moved=false;dragging=false;hold=()->{dragging=true;v.performHapticFeedback(HapticFeedbackConstants.LONG_PRESS);};handler.postDelayed(hold,ViewConfiguration.getLongPressTimeout());return true;case MotionEvent.ACTION_MOVE:float dx=e.getRawX()-downX,dy=e.getRawY()-downY;if(Math.abs(dx)>slop||Math.abs(dy)>slop){moved=true;if(!dragging){handler.removeCallbacks(hold);return true;}v.setTranslationX(dx);v.setTranslationY(dy);}return true;case MotionEvent.ACTION_UP:handler.removeCallbacks(hold);if(dragging){if(e.getRawY()<removeBand){removeItem(item);return true;}float nx=startX+(e.getRawX()-downX)/Math.max(1f,getWidth());float ny=startY+(e.getRawY()-downY)/Math.max(1f,getHeight());item.x=Math.max(0,Math.min(1-item.w,nx));item.y=Math.max(0,Math.min(1-item.h,ny));if(overlaps(item,item)){item.x=startX;item.y=startY;}listener.changed();refresh();return true;}if(!moved)listener.launch(item);return true;case MotionEvent.ACTION_CANCEL:handler.removeCallbacks(hold);view.setTranslationX(0);view.setTranslationY(0);return true;default:return true;}}
 }
 private final class WidgetFrame extends FrameLayout {final WorkspaceItem item;final AppWidgetHostView host;float downRawX,downRawY,downLocalX,downLocalY,startX,startY,startW,startH;boolean longPressed,resizing;Runnable hold;final TextView grip;
  WidgetFrame(WorkspaceItem item,AppWidgetHostView host){super(WorkspaceView.this.getContext());this.item=item;this.host=host;setBackgroundColor(Color.BLACK);addView(host,new FrameLayout.LayoutParams(-1,-1));grip=new TextView(getContext());grip.setText("↘");grip.setTextColor(Color.WHITE);grip.setTextSize(24);grip.setGravity(Gravity.CENTER);grip.setBackgroundColor(0xaa000000);grip.setVisibility(GONE);FrameLayout.LayoutParams gp=new FrameLayout.LayoutParams(dp(44),dp(44),Gravity.END|Gravity.BOTTOM);addView(grip,gp);}
  @Override public boolean onInterceptTouchEvent(MotionEvent e){switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:downRawX=e.getRawX();downRawY=e.getRawY();downLocalX=e.getX();downLocalY=e.getY();startX=item.x;startY=item.y;startW=item.w;startH=item.h;longPressed=false;resizing=false;hold=()->{longPressed=true;resizing=downLocalX>getWidth()-dp(72)&&downLocalY>getHeight()-dp(72);grip.setVisibility(VISIBLE);performHapticFeedback(HapticFeedbackConstants.LONG_PRESS);};handler.postDelayed(hold,ViewConfiguration.getLongPressTimeout());return false;case MotionEvent.ACTION_MOVE:if(longPressed)return true;if(Math.abs(e.getRawX()-downRawX)>slop||Math.abs(e.getRawY()-downRawY)>slop)handler.removeCallbacks(hold);return false;case MotionEvent.ACTION_UP:case MotionEvent.ACTION_CANCEL:handler.removeCallbacks(hold);return longPressed;default:return longPressed;}}
  @Override public boolean onTouchEvent(MotionEvent e){if(!longPressed)return super.onTouchEvent(e);switch(e.getActionMasked()){case MotionEvent.ACTION_MOVE:float dx=e.getRawX()-downRawX,dy=e.getRawY()-downRawY;if(resizing){int maxW=Math.max(dp(120),WorkspaceView.this.getWidth()-getLeft());int maxH=Math.max(dp(96),WorkspaceView.this.getHeight()-getTop());FrameLayout.LayoutParams lp=(FrameLayout.LayoutParams)getLayoutParams();lp.width=Math.max(dp(120),Math.min(maxW,(int)(startW*WorkspaceView.this.getWidth()+dx)));lp.height=Math.max(dp(96),Math.min(maxH,(int)(startH*WorkspaceView.this.getHeight()+dy)));setLayoutParams(lp);}else{setTranslationX(dx);setTranslationY(dy);}return true;case MotionEvent.ACTION_UP:handler.removeCallbacks(hold);grip.setVisibility(GONE);if(!resizing&&e.getRawY()<removeBand){removeItem(item);return true;}if(resizing){item.w=Math.max(.12f,Math.min(1-item.x,getWidth()/(float)Math.max(1,WorkspaceView.this.getWidth())));item.h=Math.max(.10f,Math.min(1-item.y,getHeight()/(float)Math.max(1,WorkspaceView.this.getHeight())));if(overlaps(item,item)){item.w=startW;item.h=startH;}notifySize();}else{item.x=Math.max(0,Math.min(1-item.w,startX+(e.getRawX()-downRawX)/Math.max(1f,WorkspaceView.this.getWidth())));item.y=Math.max(0,Math.min(1-item.h,startY+(e.getRawY()-downRawY)/Math.max(1f,WorkspaceView.this.getHeight())));if(overlaps(item,item)){item.x=startX;item.y=startY;}}listener.changed();refresh();return true;case MotionEvent.ACTION_CANCEL:handler.removeCallbacks(hold);grip.setVisibility(GONE);item.x=startX;item.y=startY;item.w=startW;item.h=startH;setTranslationX(0);setTranslationY(0);refresh();return true;default:return true;}}
  void notifySize(){int wdp=Math.max(1,Math.round(getWidth()/getResources().getDisplayMetrics().density));int hdp=Math.max(1,Math.round(getHeight()/getResources().getDisplayMetrics().density));try{host.updateAppWidgetSize(null,wdp,hdp,wdp,hdp);}catch(Exception ignored){}}
 }
 private final class EmptyTouch implements OnTouchListener{float x,y;boolean moved,drawerGesture,pageGesture;int pageDirection;Runnable hold;public boolean onTouch(View v,MotionEvent e){switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:x=e.getX();y=e.getY();moved=false;drawerGesture=false;pageGesture=false;pageDirection=0;hold=()->{if(!moved){v.performHapticFeedback(HapticFeedbackConstants.LONG_PRESS);listener.emptyLongPress(x,y);}};handler.postDelayed(hold,ViewConfiguration.getLongPressTimeout());return true;case MotionEvent.ACTION_MOVE:float dx=e.getX()-x,dy=e.getY()-y;if(Math.abs(dx)>slop||Math.abs(dy)>slop){moved=true;handler.removeCallbacks(hold);if(dy<-drawerThreshold&&Math.abs(dy)>Math.abs(dx)){drawerGesture=true;return true;}if(Math.abs(dx)>pageThreshold&&Math.abs(dx)>Math.abs(dy)){pageGesture=true;pageDirection=dx<0?1:-1;return true;}}return true;case MotionEvent.ACTION_UP:handler.removeCallbacks(hold);if(drawerGesture){listener.openDrawer();return true;}if(pageGesture){goPage(currentPage+pageDirection);return true;}return true;case MotionEvent.ACTION_CANCEL:handler.removeCallbacks(hold);return true;default:return true;}}}
}
